DEBUG = TRUE

!IF "$(DEBUG)" == "TRUE"
COPT = /c /W3 /AL /Od /Zip /nologo
LOPT = /CO/NOLOGO/NOE/St:18000
LIBS = Gnu16d
!ELSE
COPT = /c /W3 /AL /Ox /Grs /Zp /nologo
LOPT = /E/F/PACKC/NOLOGO/NOE/St:18000
LIBS = Gnu16o
!ENDIF

PROG = life

all : $(PROG).exe

$(PROG).obj : $(PROG).c
  cl $(COPT) $*.c

$(PROG).exe : $(PROG).obj
  link $* $(LOPT),,NUL,$(LIBS);
